Cinema/Cinema/Cinema/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from .views import *
from django.conf import settings
from django.conf.urls.static import static
from .initcmds import *
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r"^$|^\/$|^home\/$",Cinema_home,name="home"),

    path("register/", UserCreateView.as_view(), name="register"),
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),

    path("registerg/",GestoreCreateView.as_view(), name="registerg"),

    path("gestione/", include("gestione.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
erase_db()
init_db()

Cinema/Cinema/gestione/urls.py
from django.urls import path
from .views import *

app_name = "gestione"

urlpatterns = [
    path("", gestione_home, name="home"),
    path("listafilm/", FilmListView.as_view(),name="listafilm"),
    path('listafilm/<int:pk>/', FilmDetailView.as_view(), name='dettagli_film'),

    path('listafilm/<int:pk>/proiezioni/', FilmProjectionsView.as_view(), name='proiezioni_film'),
    path('film/<int:pk>/proiezioni_per_data/', FilmProjectionsByDateView.as_view(), name='lista_proiezioni_per_data'),
    path('film/<int:film_id>/proiezioni_per_data/<str:data>/', FilmProiezioniPerDataView.as_view(), name='film_proiezioni_per_data'),

    path("ricerca/", search, name="cercafilm"),
    path('my_situation/', my_situation, name='my_situation'),
    path('prenota_proiezione/<int:proiezione_id>/', prenota_proiezione, name='prenota_proiezione'),
    path('film/consigliati/', film_consigliati_view, name='film_consigliati'),

    path("crea_film/",CreateFilmView.as_view(),name="creafilm"),
    path("crea_proiezione/",CreateProiezioneView.as_view(),name="creaproiezione"),
]

Cinema/Cinema/gestione/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django.core.exceptions import ValidationError
from datetime import date, time
import re
from .models import *

class CreateFilmForm(forms.ModelForm):
    helper = FormHelper()
    helper.form_id = "addfilm_crispy_form"
    helper.form_method = "POST"
    helper.add_input(Submit("submit","Aggiungi Film"))

    class Meta:
        model = Film
        fields = ["titolo","genere","descrizione", "prezzo", "immagine", "in_3D", "in_inglese"]

class CreateProiezioneForm(forms.ModelForm):
    helper = FormHelper()
    helper.form_id = "addproiezione_crispy_form"
    helper.form_method = "POST"
    helper.add_input(Submit("submit","Aggiungi Proiezione"))

    class Meta:
        model = Proiezione
        fields = ["data", "ora_inizio", "film", "sala", "posti_disponibili"]
    
    def clean(self):
        cleaned_data = super().clean()
        data = cleaned_data.get("data")
        ora_inizio = cleaned_data.get("ora_inizio")
        sala = cleaned_data.get("sala")

        if data and ora_inizio and sala:
            overlapping_proiezioni = Proiezione.objects.filter(
                data=data,
                ora_inizio=ora_inizio,
                sala=sala
            )
            if overlapping_proiezioni.exists():
                raise ValidationError(
                    "Esiste già una proiezione nella sala selezionata alla data e ora specificate."
                )

        return cleaned_data


    def clean_data(self):
        data = self.cleaned_data.get("data")
        if data and data < date.today():
            raise ValidationError("La data della proiezione deve essere futura.")
        return data
    
    def clean_posti_disponibili(self):
        posti_disponibili = self.cleaned_data.get("posti_disponibili")
        if posti_disponibili > 100:  # Suppongo che il massimo dei posti sia 100
            raise ValidationError("Il numero di posti disponibili non può superare 100.")
        elif posti_disponibili == 0:
            raise ValidationError("Inserire almeno un posto disponibile")
        elif posti_disponibili < 0:
            raise ValidationError("Formato non valido. Inserire un numero positivo di posti")
        return posti_disponibili

    def clean_ora_inizio(self):
        ora_inizio = self.cleaned_data.get("ora_inizio")
        start_time = time(14, 0)  # 14:00
        end_time = time(22, 0)    # 22:00
        if ora_inizio < start_time or ora_inizio > end_time:
            raise ValidationError("L'ora di inizio deve essere compresa tra le 14:00 e le 22:00")
        return ora_inizio

    def clean_sala(self):
        sala = self.cleaned_data.get("sala")
        pattern = r"^Sala ([1-8])$"
        match = re.match(pattern, sala)
        if not match:
            raise ValidationError("La sala deve essere compresa tra Sala 1 e Sala 8 nel formato 'Sala X'.")
        return sala
    

Cinema/Cinema/gestione/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from .models import *
from .forms import *
from django.utils import timezone
from datetime import datetime
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib import messages
from django.urls import reverse
from django.urls import reverse_lazy

# Create your views here.

def gestione_home(request):
    return render(request,template_name="gestione/home.html")

class FilmListView(ListView):
    titolo = "Il nostro cinema offre attualmente i seguenti film: "
    model = Film
    template_name = "gestione/lista_film.html"
    context_object_name = 'object_list'

    def get_queryset(self):
        queryset = super().get_queryset()

        # Recupera i parametri di filtro dalla richiesta GET
        filter_category = self.request.GET.get('filter_category', None)
        filter_value = self.request.GET.get('filter_value', None)
        filter_date = self.request.GET.get('filter_date', None)

        if filter_category == 'genere' and filter_value:
            queryset = queryset.filter(genere=filter_value)
        elif filter_category == 'extra' and filter_value:
            if filter_value == 'in_3D':
                queryset = queryset.filter(in_3D=True)
            elif filter_value == 'in_inglese':
                queryset = queryset.filter(in_inglese=True)
        elif filter_category == 'data' and filter_date:
            try:
                # Filtraggio dei film con proiezioni per la data selezionata
                date = datetime.strptime(filter_date, "%Y-%m-%d")
                # Filtriamo i film in base alle proiezioni con data uguale alla data selezionata
                # Otteniamo tutti gli ID dei film con proiezioni nella data selezionata
                film_ids_with_projections = Proiezione.objects.filter(data=date).values_list('film_id', flat=True)
                # Filtriamo i film per includere solo quelli con proiezioni nella data selezionata
                queryset = queryset.filter(id__in=film_ids_with_projections)
            except ValueError:
                print("Problemi nel filtraggio per data")
        return queryset       


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['generi'] = list(Film.objects.values_list('genere', flat=True).distinct())
        context['filter_category'] = self.request.GET.get('filter_category', '')
        context['filter_value'] = self.request.GET.get('filter_value', '')
        context['filter_date'] = self.request.GET.get('filter_date', '')
        return context


def search(request):
    query = request.GET.get('search_title')
    context = {'search_title': query}
    
    if query:
        films = Film.objects.filter(titolo__icontains=query)
        if films.exists():
            film = films.first()
            # Filtra le proiezioni con data presente o futura
            proiezioni_dates = Proiezione.objects.filter(film=film, data__gte=date.today()).values('data').distinct()
            context.update({
                'film': film,
                'proiezioni_dates': proiezioni_dates,
            })
        else:
            context['film_not_found'] = True
    
    return render(request, 'gestione/cerca_film.html', context)

class FilmDetailView(DetailView):
    model = Film
    template_name = 'gestione/dettagli_film.html'

class FilmProjectionsView(ListView):
    model = Proiezione
    template_name = 'gestione/proiezioni_film.html'
    context_object_name = 'proiezioni'

    def get_queryset(self):
        film_id = self.kwargs['pk']
        today = date.today() 
        return Proiezione.objects.filter(film_id=film_id, data__gte=today)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['film'] = Film.objects.get(pk=self.kwargs['pk'])
        return context

class FilmProjectionsByDateView(TemplateView):
    template_name = "gestione/lista_proiezioni_per_data.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        film = get_object_or_404(Film, pk=self.kwargs['pk'])
        filter_date = self.request.GET.get('filter_date')

        try:
            date = datetime.strptime(filter_date, "%Y-%m-%d")
            if date < date.today():
                # Se la data è nel passato non mostro nessuna proiezione
                proiezioni = Proiezione.objects.none()
            else:
                # Se la data è nel futuro o è oggi
                # Ottieni le proiezioni per il film e la data specificata
                proiezioni = Proiezione.objects.filter(film=film, data=date)
        except (ValueError, TypeError):
            proiezioni = Proiezione.objects.none()

        context['film'] = film
        context['filter_date'] = filter_date
        context['proiezioni'] = proiezioni
        return context


class FilmProiezioniPerDataView(ListView):
    model = Proiezione
    template_name = 'gestione/proiezioni_per_data.html'
    context_object_name = 'proiezioni'

    def get_queryset(self):
        film_id = self.kwargs['film_id']
        data = self.kwargs['data']
        # Verifica che la data sia presente o futura
        if data < str(date.today()):
            return Proiezione.objects.none()  # Nessuna proiezione se la data è nel passato
        return Proiezione.objects.filter(film_id=film_id, data=data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        film = get_object_or_404(Film, pk=self.kwargs['film_id'])
        context['film'] = film
        context['data'] = self.kwargs['data']
        return context
        
@login_required
def my_situation(request):
    utente = get_object_or_404(Utente, pk=request.user.pk)
    prenotazioni = utente.get_prenotazioni()
    context = {
        'prenotazioni': prenotazioni
    }
    return render(request, 'gestione/my_situation.html', context)


def build_redirect_url(view_name, kwargs, filter_date):
    url = reverse(view_name, kwargs=kwargs)
    if filter_date:
        url += f"?filter_date={filter_date}"
    return url


@login_required
def prenota_proiezione(request, proiezione_id):
    proiezione = get_object_or_404(Proiezione, pk=proiezione_id)
    utente = request.user

    # Recuperiamo i parametri GET
    next_url = request.GET.get('next')
    filter_date = request.GET.get('filter_date')
    
    # Costruisci l'URL di reindirizzamento
    if next_url:
        if 'film_proiezioni_per_data' in next_url:
            film_id = proiezione.film.pk
            data = filter_date if filter_date else proiezione.data
            next_url = build_redirect_url('gestione:film_proiezioni_per_data', {'film_id': film_id, 'data': data}, filter_date)
        elif 'lista_proiezioni_per_data' in next_url:
            film_id = proiezione.film.pk
            next_url = f"{reverse('gestione:lista_proiezioni_per_data', kwargs={'pk': film_id})}?filter_date={filter_date}"
        elif 'proiezioni_film' in next_url:
            film_id = proiezione.film.pk
            next_url = reverse('gestione:proiezioni_film', kwargs={'pk': film_id})
    else:
        next_url = reverse('gestione:home')  # Redirezione di default alla home se next non è fornito

    # Controllo se ci sono posti disponibili
    if proiezione.posti_disponibili <= 0:
        messages.error(request, 'Non ci sono posti disponibili per questa proiezione.')
        return redirect(next_url)

    # Controllo se l'utente ha già una prenotazione per la stessa data e ora in una sala differente
    esiste_prenotazione = Prenotazione.objects.filter(
        utente=utente,
        proiezione__data=proiezione.data,
        proiezione__ora_inizio=proiezione.ora_inizio,
    ).exclude(proiezione__sala=proiezione.sala).exists()
    
    if esiste_prenotazione:
        messages.error(request, 'Prenotazione fallita. Hai già una prenotazione alla stessa ora per un\'altra proiezione in una sala differente.')
        return redirect(next_url)

    # Creazione della prenotazione
    Prenotazione.objects.create(utente=utente, proiezione=proiezione)
    proiezione.posti_disponibili -= 1
    proiezione.save()

    messages.success(request, 'Prenotazione effettuata con successo!')
    return redirect(next_url)

@login_required
def film_consigliati_view(request):
    utente = request.user
    film_consigliati = utente.get_film_consigliati()
    return render(request, 'gestione/film_consigliati.html', {'film_consigliati': film_consigliati})

#Views per soli Gestori e Admin
class CreateFilmView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    group_required = ["Gestori"]
    title = "Aggiungi un film al cinema"
    form_class = CreateFilmForm
    template_name = "gestione/create_entry.html"
    success_url = reverse_lazy("gestione:home")

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, "Il film è stato aggiunto con successo!")
        return response
    
    def test_func(self):
        # Controlla se l'utente appartiene al gruppo "Gestori" o se è un superuser
        return self.request.user.groups.filter(name='Gestori').exists() or self.request.user.is_superuser

class CreateProiezioneView(CreateFilmView):
    title = "Aggiungi una Proiezione ad un film"
    form_class = CreateProiezioneForm

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, "La proiezione è stata aggiunta con successo!")
        return response

Cinema/Cinema/gestione/templates/gestione/cerca_film.html
{% extends 'basebs.html' %}

{% block title %} Cerca un film{% endblock %} 

{% block header1 %}
  <h1>Cerca un film</h1>
{% endblock %}

{% block content %} 
    <form method="GET" action="{% url 'gestione:cercafilm' %}">
        <input type="text" name="search_title" placeholder="Cerca per titolo" value="{{ search_title }}">
    <button type="submit">Cerca</button>
  </form>
  <br>
  {% if film_not_found %}
    <p>Nessun film trovato con il titolo "{{ search_title }}".</p>
  {% elif film %}
    <h2>Risultati della ricerca per:<h2><br>
    <h2>{{ film.titolo }}</h2>

    {% if proiezioni_dates %}
      <div class="row">
        {% for proiezione_date in proiezioni_dates %}
          <div class="col-md-4">
            <div class="card mb-4">
              <div class="card-body">
                <h5 class="card-title">{{ proiezione_date.data|date:"d/m/Y" }}</h5>
                <a href="{% url 'gestione:film_proiezioni_per_data' film.id proiezione_date.data %}" class="btn btn-primary">Visualizza proiezioni</a>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    {% else %}
      <p>Non ci sono proiezioni previste per questo film.</p>
    {% endif %}
  {% elif search_title %}
    <p>Nessun film trovato con il titolo "{{ search_title }}".</p>
  {% endif %}
{% endblock %}

Cinema/Cinema/gestione/templates/gestione/film_consigliati.html
{% extends 'basebs.html' %}

{% block title %} Film Consigliati per Te {% endblock %}

{% block header1 %}
  <h1> Film Consigliati per Te </h1>
{% endblock %}

{% block content %}
<div class="container">
    <h1>Film Consigliati per Te</h1>
    <div class="row">
        {% for film in film_consigliati %}
            <div class="col-md-4">
                <div class="card mb-4 shadow-sm">
                    <img src="{{ film.immagine.url }}" class="card-img-top" alt="{{ film.titolo }}">
                    <div class="card-body">
                        <h5 class="card-title">{{ film.titolo }}</h5>
                        <p class="card-text">{{ film.descrizione }}</p>
                        <p class="card-text"><strong>Genere:</strong> {{ film.genere }}</p>
                        <p class="card-text"><strong>Prezzo:</strong> €{{ film.prezzo }}</p>
                        {% if film.in_3D %}
                            <p class="card-text"><strong>3D</strong></p>
                        {% endif %}
                        {% if film.in_inglese %}
                            <p class="card-text"><strong>In Inglese</strong></p>
                        {% endif %}
                        <a href="{% url 'gestione:dettagli_film' film.id %}" class="btn btn-primary">Dettagli</a>
                    </div>
                </div>
            </div>
        {% empty %}
            <p>Non ci sono film consigliati al momento.</p>
        {% endfor %}
    </div>
</div>
{% endblock %}

Cinema/Cinema/gestione/templates/gestione/home.html
{% extends 'basebs.html' %}

{% block title %} Home di Gestione {% endblock %} 

{% block header1 %}
  <h1>Home di Gestione</h1>
  <p>Welcome 
    {% if user.is_authenticated %}
     {{ user.username }}
    {% else %}
    Utente non registrato
    {% endif %}
  </p> 
{% endblock %}

{% block content %} 

<h2>Cosa vuoi fare oggi?</h2>

<br>

<div class="list-group">
  <a href="{% url 'gestione:cercafilm' %}" class="list-group-item list-group-item-info">Cerca un film</a>
  <a href="{% url 'gestione:listafilm' %}" class="list-group-item list-group-item-info">Lista dei film con filtri</a>
  <a href="{% url 'gestione:cercafilm' %}" class="list-group-item list-group-item-info">Effettua prenotazione</a>
  <a href="{% url 'gestione:my_situation' %}" class="list-group-item list-group-item-info">La mia situazione</a>
  <a href="{% url 'gestione:film_consigliati'%}" class="list-group-item list-group-item-info">Film Consigliati per te</a>
</div>

<br>

{% if user.is_staff %}
<br>
<a href="{% url 'registerg' %}" class="list-group-item list-group-item-danger">Iscrivi un gestore</a>
<br>
{% endif %}


{% if "Gestori" in user.groups.all.0.name or user.is_staff %}
<br>
<a href="{% url 'gestione:creafilm' %}" class="list-group-item list-group-item-warning">Aggiungi un film</a>
<a href="{% url 'gestione:creaproiezione' %}" class="list-group-item list-group-item-warning">Aggiungi una proiezione</a>
<br>
{% endif %}


{% endblock %}

Cinema/Cinema/gestione/templates/gestione/lista_film.html
{% extends 'basebs.html' %}

{% block title %} Lista dei film con filtri{% endblock %} 

{% block header1 %}
  <h1>Lista dei Film con filtri</h1>
{% endblock %}

{% block content %} 

    <h2> {{ view.titolo }} </h2>
    {% if filter_category and filter_value %}
        <h3> {{ object_list.count }} film trovati </h3>
    {%elif filter_category and filter_date%}
        <h3> {{ object_list.count }} film trovati </h3>
    {% else %}
        <h3> Seleziona un filtro per visualizzare i film attualmente disponibili <h3>
    {% endif %}

    <br>

    <!-- Form di filtraggio -->
    <form method="get">
        <div class="form-group">
            <label for="filter_category">Filtra per:</label>
            <select id="filter_category" name="filter_category" class="form-control" onchange="updateFilterOptions()">
                <option value="">Seleziona una categoria</option>
                <option value="genere" {% if filter_category == "genere" %}selected{% endif %}>Genere</option>
                <option value="extra" {% if filter_category == "extra" %}selected{% endif %}>Caratteristiche Extra</option>
                <option value="data" {% if filter_category == "data" %}selected{% endif %}>Data</option>
            </select>
        </div>
        <div class="form-group" id="filter_value_container" style="display:none;">
            <label for="filter_value">Valore:</label>
            <select id="filter_value" name="filter_value" class="form-control">
            </select>
        </div>
        <div class="form-group" id="filter_date_container" style="display:none;">
            <label for="filter_date">Seleziona Data:</label>
            <input type="date" id="filter_date" name="filter_date" class="form-control">
        </div>
        <button type="submit" class="btn btn-primary">Filtra</button>
    </form>

    <br>

    <!-- Lista dei film -->
    {% if filter_category %}
        {% if filter_value or filter_date %} 
            {% if object_list %}
                <div class="row">
                    {% for film in object_list %}
                        <div class="col-md-4">
                            <div class="card mb-4 shadow-sm">
                                <div class="card-body">
                                    <h5 class="card-title">{{ film.titolo }}</h5>
                                    <p class="card-text">
                                        Genere: {{ film.genere }}<br>
                                        Prezzo: €{{ film.prezzo }}
                                    </p>
                                    <div class="d-flex justify-content-between align-items-center">
                                        <div class="btn-group">
                                            <a href="{% url 'gestione:dettagli_film' film.pk %}" class="btn btn-sm btn-outline-secondary">Dettagli</a>
                                            {% if filter_category == 'data' and filter_date %}
                                                <a href="{% url 'gestione:lista_proiezioni_per_data' film.pk %}?filter_date={{ filter_date }}" class="btn btn-sm btn-outline-secondary">Proiezioni per data</a>
                                            {% else %}
                                                <a href="{% url 'gestione:proiezioni_film' film.pk %}" class="btn btn-sm btn-outline-secondary">Proiezioni</a>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% else %}
                <p>Nessun film trovato con il filtro selezionato.</p>
            {% endif %}
        {% else %}
            <p>Per favore, seleziona un valore per il filtro.</p>
        {% endif %}
    {% else %}
        <p>Per favore, seleziona un filtro per visualizzare i film.</p>
    {% endif %}

    <script>

        const generi = JSON.parse('{{ generi|escapejs|safe }}');

        function updateFilterOptions() {
            const filterCategory = document.getElementById('filter_category').value;
            const filterValueContainer = document.getElementById('filter_value_container');
            const filterDateContainer = document.getElementById('filter_date_container');
            const filterValueSelect = document.getElementById('filter_value');

            filterValueSelect.innerHTML = ''; // Resetta le opzioni
            filterDateContainer.style.display = 'none';
            filterValueContainer.style.display = 'none';

            if (filterCategory === 'genere') {
                filterValueContainer.style.display = 'block';
                filterValueSelect.innerHTML = `
                    <option value="">Seleziona un genere</option>
                    <option value="Fantasy">Fantasy</option>
                    <option value="Fantascienza">Fantascienza</option>
                    <option value="Animazione">Animazione</option>
                    <option value="Romantico">Romantico</option>
                    <option value="Giallo">Giallo</option>
                    <option value="Azione">Azione</option>
                `;
            } else if (filterCategory === 'extra') {
                filterValueContainer.style.display = 'block';
                filterValueSelect.innerHTML = `
                    <option value="">Seleziona una caratteristica</option>
                    <option value="in_3D">3D</option>
                    <option value="in_inglese">In inglese</option>
                `;
            } else if (filterCategory === 'data') {
                filterDateContainer.style.display = 'block';
            } else {
                filterValueContainer.style.display = 'none';
            }
        }

        document.addEventListener('DOMContentLoaded', function() {
            updateFilterOptions(); // Mi assicuro che le opzioni siano corrette al caricamento della pagina
        });
    </script>
{% endblock %}

Cinema/Cinema/gestione/templates/gestione/lista_proiezioni_per_data.html
{% extends 'basebs.html' %}

{% block title %}Proiezioni di {{ film.titolo }} per la data selezionata{% endblock %}

{% block header1 %}
    <h1>Proiezioni di {{ film.titolo }} per la data selezionata</h1>
{% endblock %}

{% block content %}
    <h2>Proiezioni programmate per il {{ filter_date }}</h2>
    <br>
    
    {% if proiezioni %}
        <div class="row">
            {% for proiezione in proiezioni %}
                <div class="col-md-4">
                    <div class="card mb-4 shadow-sm">
                        <div class="card-body">
                            <h5 class="card-title">{{ film.titolo }}</h5>
                            <p class="card-text">
                                Data: {{ proiezione.data|date:"d/m/Y" }}<br>
                                Ora di inizio: {{proiezione.ora_inizio|date:"H:i" }} <br>
                                Sala: {{ proiezione.sala }} <br>
                                Posti disponibili: {{ proiezione.posti_disponibili }} <br>
                                <a href="{% url 'gestione:prenota_proiezione' proiezione.id %}?next={% url 'gestione:home' %}" class="btn btn-primary">Prenota</a>
                            </p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p>Non ci sono proiezioni previste per la data selezionata.</p>
    {% endif %}
{% endblock %}

Cinema/Cinema/gestione/templates/gestione/proiezioni_film.html
{% extends 'basebs.html' %}

{% block title %}Proiezioni del film{% endblock %}

{% block header1 %}
  <h1>Proiezioni del film</h1>
{% endblock %}

{% block content %}
    <h1>Proiezioni per {{ film.titolo }}</h1>
    
    <h2>Proiezioni programmate</h2>
    <br>
    
    {% if proiezioni %}
        <div class="row">
            {% for proiezione in proiezioni %}
                <div class="col-md-4">
                    <div class="card mb-4 shadow-sm">
                        <div class="card-body">
                            <h5 class="card-title">{{ film.titolo }}</h5>
                            <p class="card-text">
                                Data: {{ proiezione.data|date:"d/m/Y" }}<br>
                                Ora di inizio: {{proiezione.ora_inizio|date:"H:i" }} <br>
                                Sala: {{ proiezione.sala }} <br>
                                Posti disponibili: {{ proiezione.posti_disponibili }} <br>
                                <a href="{% url 'gestione:prenota_proiezione' proiezione.id %}?next={% url 'gestione:proiezioni_film' film.pk %}" class="btn btn-primary">Prenota</a>
                            </p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p>Nessuna proiezione trovata.</p>
    {% endif %}
{% endblock %}

Cinema/Cinema/gestione/templates/gestione/proiezioni_per_data.html
{% extends 'basebs.html' %}

{% block title %}Proiezioni per {{ film.titolo }} il {{ data }}{% endblock %}

{% block header1 %}
  <h1>Proiezioni per {{ film.titolo }} il {{ data }}</h1>
{% endblock %}

{% block content %}
  {% if proiezioni %}
    <div class="row">
      {% for proiezione in proiezioni %}
        <div class="col-md-4">
          <div class="card mb-4">
            <div class="card-body">
                <h5 class="card-title">Ora di inizio: {{proiezione.ora_inizio|date:"H:i" }}</h5>
                <p class="card-text">Sala: {{ proiezione.sala }}</p>
                <p class="card-text">Posti disponibili: {{ proiezione.posti_disponibili }}</p>
                <a href="{% url 'gestione:prenota_proiezione' proiezione.id %}?next={{ request.path }}" class="btn btn-primary">Prenota</a>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  {% else %}
    <p>Non ci sono proiezioni per questa data.</p>
  {% endif %}
{% endblock %}