Cinema/Cinema/Cinema/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from .views import *
from django.conf import settings
from django.conf.urls.static import static
from .initcmds import *
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r"^$|^\/$|^home\/$",Cinema_home,name="home"),

    path("register/", UserCreateView.as_view(), name="register"),
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),

    path("registerg/",GestoreCreateView.as_view(), name="registerg"),

    path("gestione/", include("gestione.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
erase_db()
init_db()

Cinema/Cinema/gestione/urls.py
from django.urls import path
from .views import *

app_name = "gestione"

urlpatterns = [
    path("", gestione_home, name="home"),
    path("listafilm/", FilmListView.as_view(),name="listafilm"),
    path('listafilm/<int:pk>/', FilmDetailView.as_view(), name='dettagli_film'),

    path('listafilm/<int:pk>/proiezioni/', FilmProjectionsView.as_view(), name='proiezioni_film'),
    path('film/<int:pk>/proiezioni_per_data/', FilmProjectionsByDateView.as_view(), name='lista_proiezioni_per_data'),
    path('film/<int:film_id>/proiezioni_per_data/<str:data>/', FilmProiezioniPerDataView.as_view(), name='film_proiezioni_per_data'),

    path("ricerca/", search, name="cercafilm"),
    path('my_situation/', my_situation, name='my_situation'),
    path('prenota_proiezione/<int:proiezione_id>/', prenota_proiezione, name='prenota_proiezione'),
    path('film/consigliati/', film_consigliati_view, name='film_consigliati'),

    path("crea_film/",CreateFilmView.as_view(),name="creafilm"),
    path("crea_proiezione/",CreateProiezioneView.as_view(),name="creaproiezione"),
]

Cinema/Cinema/templates/basebs.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %} 
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
  <style>
  .fakeimg {
    height: 200px;
    background: #aaa;
  }
  </style>
  {% endblock %}
  {% load crispy_forms_tags %} 

</head>


<title>{% block title %} {% endblock %}</title> 

<body>

<div class="jumbotron text-center" style="margin-bottom:0">
{% block header1 %}
  <h1>Header</h1>
  <p>Subtitle</p> 
{% endblock %}
</div>

{% if user.is_authenticated and "ok" in request.GET.login  %}

<div id="info" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Welcome {{user.username}} </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p> La procedura di login è andata a buon fine </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-info" data-dismiss="modal">Chiudi</button>
      </div>
    </div>
  </div>
</div> 
<script>
  $(document).ready(function(){
      $("#info").modal('show');
  });
</script>

{% endif %}


<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    {% block navbar %}
    <a class="navbar-brand" href="{% url 'home' %}">Cinema</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
      <ul class="navbar-nav">


        <li class="nav-item">
          <a class="nav-link" href="{% url 'gestione:home' %}">Gestione</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'gestione:listafilm' %}">Lista dei Film</a>
        </li>
        
        <li class="nav-item">
          <a class="nav-link" href="{% url 'gestione:cercafilm' %}">Cerca un Film</a>
        </li>

      </ul>
    </div> 
    {% endblock %} 
  </nav>

  {% if messages %}
        <div>
            {% for message in messages %}
                <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">
                    {{ message }}
                </div>
            {% endfor %}
        </div>
    {% endif %}

  
  <div class="container" style="margin-top:30px">
    
      <div class="col-sm-22">
        <center>

        {% block content %}
        <h2>TITLE HEADING</h2>
        <h5>Title description, Dec 7, 2017</h5>
        <div class="fakeimg">Fake Image</div>
        <p>Some text..</p>
        <p>Sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.</p>
        {% endblock %}
        <br>
        </center>
      </div>
    </div>
  

  <div class="jumbotron text-center" style="margin-bottom:0">
    {% block footer %} 

      {% if user.is_authenticated %}

      <form id="logout-form" method="post" action="{% url 'logout' %}">   
      {% csrf_token %}
      <button type="submit" class="btn btn-info">Log out</button>
      </form>
      </br>
      {% else %}
      <a class="btn btn-info" href="{% url 'register' %}" role="button">Registrati</a>
      <a class="btn btn-info" href="{% url 'login' %}" role="button">Login</a>
      {% endif %}

      <a class="btn btn-warning" href="/admin/" role="button">Admin Login</a>
   
    {%  endblock %}
  </div>
  
    
  </body>
  </html>

Cinema/Cinema/templates/home.html
{% extends 'basebs.html' %}

{% load static %}

{% block title %} Home di Cinema {% endblock %} 

{% block header1 %}
  <h1>Home di Cinema</h1>
  <p>Pagina iniziale del cinema.</p> 
{% endblock %}

{% block content %} 

<h2>Homepage Cinema</h2>
<img src="{% static '/imgs/Cinema.jpeg' %}" width="800"  height="400px" alt="cinema">
<p>Comincia la navigazione</p>

{% endblock %}

Cinema/Cinema/templates/user_create.html
{% extends 'basebs.html' %}

{% load crispy_forms_tags %} 
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> 

{% block title %} Creazione Utente {{ form.user_group_name }} {% endblock %} 

{% block header1 %}
  <h1>Pagina di Registrazione</h1>
  <p>Si prega di compilare i campi necessari</p> 
{% endblock %}

{% block content %} 

<form method="post"> {% csrf_token %}

  {{form | crispy}}
  
  <input type="submit" class="btn btn-success" value="Registrati ora!">
  
  </form>

{% endblock %}

{% block footer %} {% endblock %}